###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine

    mailhog:
      image: mailhog/mailhog:latest
      ports:
        - "8025:8025"

    redis:
      image: redis:alpine
      #container_name: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data

    mysql:
      image: mysql:8.0
      working_dir: /application
      volumes:
        # - .:/application/mystore
        - db-data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=outlet
        - MYSQL_DATABASE=outlet
        - MYSQL_USER=outlet
        - MYSQL_PASSWORD=outlet
      ports:
        - "3307:3306"

    clickhouse:
      image: yandex/clickhouse-server:latest

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
      container_name: elasticsearch
      environment:
        - node.name=es01
        - cluster.name=es-docker-cluster
        - discovery.seed_hosts=es02,es03
        - cluster.initial_master_nodes=es01,es02,es03
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.ml.enabled=false
        - xpack.graph.enabled=false
        - xpack.watcher.enabled=false
        - discovery.zen.minimum_master_nodes=1
        - discovery.type=single-node
        #- cluster.name=docker-cluster
      ulimits:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - data01:/usr/share/elasticsearch/data
        #- elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - 9300:9200
      networks:
        - elasticnet
    
    kibana:
      image: docker.elastic.co/kibana/kibana:7.5.2
      container_name: kibana
      restart: always
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      ports:
        - 5602:5601
      depends_on:
        - elasticsearch
      networks:
        - elasticnet

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
        - "443:443"
        - "32823:22"
      links:
        - mysql:mysql
        - elasticsearch:elasticsearch
        - redis:redis
        - mailhog:mailhog
        - memcached:memcached
        - kibana:kibana
      depends_on:
        - mysql
        - elasticsearch
        - redis
        - mailhog
        - memcached
        - kibana

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      environment:
        MYSQL_USERNAME: outlet
        MYSQL_ROOT_PASSWORD: outlet
        PMA_HOST: mysql
      ports:
        - 8004:80
      links:
        - mysql:mysql
        - elasticsearch:elasticsearch
        - redis:redis
        - mailhog:mailhog
        - memcached:memcached
      depends_on:
        - mysql
        - elasticsearch
        - redis
        - mailhog
        - memcached

volumes:
  data01:
    external: false
  #elasticsearch-data:
    driver: local
  db-data:
    external: false
  redis-data:
    external: false

networks:
  elasticnet:
    driver: bridge